[en]
title = "Let's Encrypt - Free SSL/TLS Certificates"
contentDir = "content/en"
languageName ="English"
languageCode= "en-us"
#if colon ":" must be prefixed
beforeColon= ""
# Weight used for sorting. MUST BE +10 than the previous language
weight = 10
description = """
  Let&rsquo;s&nbsp;Encrypt is a free, automated, and open certificate
  authority brought to you by the non-profit <a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a>.
"""
[fr]
title = "Let's Encrypt - Certificats SSL/TLS gratuits"
languageName = "Français"
contentDir = "content/fr"
languageCode= "fr-fr"
beforeColon= "&nbsp;"
weight = 20
description = """
  Let&rsquo;s&nbsp;Encrypt est une autorité de certification gratuite, automatisée et ouverte
  apporté par l'<a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a>, organisme à but non lucratif.
"""

[es]
title = "Let's Encrypt - Certificados SSL/TLS Gratuitos"
contentDir = "content/es"
languageName ="Español"
languageCode= "es-us"
beforeColon= "&nbsp;"
weight = 30
description = """
  Let&rsquo;s&nbsp;Encrypt es una autoridad de certificación gratuita, automatizada, y abierta traida a ustedes por la organización sin ánimos de lucro <a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a>.
"""

[ru]
title = "Let's Encrypt - Free SSL/TLS Certificates"
contentDir = "content/ru"
languageName ="Русский"
languageCode= "ru-ru"
beforeColon= ""
weight = 60
description = """
  Let&rsquo;s&nbsp;Encrypt - это бесплатный, автоматизированный и открытый Центр Сертификации, созданный для вас
  некоммерческой организацией <a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a>.
"""

[de]
title = "Let's Encrypt - Freie SSL/TLS Zertifikate"
contentDir = "content/de"
languageName ="Deutsch"
languageCode= "de-de"
beforeColon= ""
weight = 50
description = """
  Let&rsquo;s&nbsp;Encrypt ist eine freie, automatisierte und offene Zertifizierungsstelle,
  herausgebracht für Sie durch <a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a>.
"""

[zh-cn]
title = "Let's Encrypt - 免费SSL/TLS证书"
languageName = "简体中文"
contentDir = "content/zh-cn"
languageCode= "zh-cn"
beforeColon= ""
weight = 40
description = """
  Let's Encrypt 是由非营利性互联网安全研究组（ISRG）提供给您的免费，自动化和开放的证书颁发机构。
"""

[pt-br]
title = "Let's Encrypt - Certificados SSL/TLS Gratuitos"
contentDir = "content/pt-br"
languageName ="Português do Brasil"
languageCode= "pt-br"
beforeColon= ""
weight = 70
description = """
  Let&rsquo;s&nbsp;Encrypt é uma autoridade certificadora gratuita, automatizada e aberta
  que se tornou possível graças à organização sem fins lucrativos <a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a>
"""
